# Gitlab repository link: https://github.com/Natilorens/Workshop-CI-Entrega-02

stages:
  - build
  - test
  - deploy


frontend-build:
  image: node:latest
  stage: build
  before_script:
    - cd frontend
  script:
    - yarn

backend-build:
  image: node:latest
  stage: build
  before_script:
    - cd backend
    - npm install
  script:
    - npm run build

frontend-test:
  image: node:latest
  stage: test
  before_script:
    - cd frontend
    - yarn
  script:
    - yarn test

backend-test:
  image: node:latest
  stage: test
  before_script:
    - cd backend
    - npm install
  script:
    - npm run unittest

image: docker:latest
services:
  - docker:dind

frontend-deploy:
  stage: deploy
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script: 
    - docker build -t natilorens/frontend ./frontend -f ./frontend/Dockerfile
    - docker push natilorens/frontend


backend-deploy:
  stage: deploy
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script: 
    - docker build -t natilorens/backend ./backend -f ./backend/Dockerfile
    - docker push natilorens/backend



