stages:
  - build
  - test
  - deploy

frontend-build:
  image: node:latest
  stage: build
  script:
    - yarn

backend-build:
  image: node:latest
  stage: build
  before_script:
    - cd backend
  
  script:
    - npm run build


